version: "3"

services:
  postgres:
    image: postgres
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    ports:
      - "${POSTGRESQL_PORT}:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
  pact_broker:
    image: dius/pact-broker
    ports:
      - "${PACT_PORT}:80"
    links:
      - postgres
    environment:
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: password
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: postgres
      PACT_BROKER_WEBHOOK_SCHEME_WHITELIST: http https
  localstack:
    image: localstack/localstack
    ports:
      - "${LOCALSTACK_PORT}:4566"
    environment:
      - SERVICES=sqs,sns
      - DEFAULT_REGION=eu-central-1
      - DEBUG=1
    volumes:
      - "./localstack_setup.sh:/docker-entrypoint-initaws.d/setup.sh"
    hostname: localstack
